### ISSUE TITLE
NPM Install

### ISSUE THREAD

**Issue by oyinda-subair** [BolajiOlajide/ng-faker#17]
Using `npm install` to install dependencies before running `npm run test` returns this error
```npm run test                                                                                                                                        

> ng-faker@1.0.0 test /Users/oyindamolasubair/Workspace/ng-faker
> ./tests/test.sh

yarn run v1.5.1
$ ./node_modules/.bin/eslint .
✨  Done in 4.52s.
TypeError: (0 , (_jestUtil || _load_jestUtil(...)).validateCLIOptions) is not a function
    at buildArgv (/Users/oyindamolasubair/Workspace/ng-faker/node_modules/jest-cli/build/cli/index.js:133:58)
    at Object.<anonymous> (/Users/oyindamolasubair/Workspace/ng-faker/node_modules/jest-cli/build/cli/index.js:41:20)
    at next (native)
    at step (/Users/oyindamolasubair/Workspace/ng-faker/node_modules/jest-cli/build/cli/index.js:53:2732)
    at /Users/oyindamolasubair/Workspace/ng-faker/node_modules/jest-cli/build/cli/index.js:53:2962
    at Object.<anonymous> (/Users/oyindamolasubair/Workspace/ng-faker/node_modules/jest-cli/build/cli/index.js:53:2643)
    at Object.run (/Users/oyindamolasubair/Workspace/ng-faker/node_modules/jest-cli/build/cli/index.js:53:48)
    at Object.<anonymous> (/Users/oyindamolasubair/Workspace/ng-faker/node_modules/jest-cli/bin/jest.js:16:27)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ng-faker@1.0.0 test: `./tests/test.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ng-faker@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by BolajiOlajide** [comment]
Still trying to replicate this.

It works perfectly on my PC and it was given the error initially on @andela-rbabalola's PC but it mysteriously started working itself.

**Comment by BolajiOlajide** [comment]
@oyinda-subair Can you please share your node version and npm version?
