### ISSUE TITLE
ngfaker.name.fullName fails with an invalid locale

### ISSUE THREAD

**Issue by rotimi-babalola** [BolajiOlajide/ng-faker#22]
Steps to reproduce
- Set an invalid locale e.g. `ngfaker.setLocale('gkgkf');`
- Try to generate a full name e.g. `ngfaker.name.fullName()`
- This error shows up
```/Users/rotimi/Documents/ng-faker/lib/name.js:40
    return ngFaker.random.arrayElement(ngFaker.locales[ngFaker.locale].name.prefix);
                                                                       ^

TypeError: Cannot read property 'name' of undefined
    at Name.prefix (/Users/rotimi/Documents/ng-faker/lib/name.js:40:72)
    at NgFaker.fake (/Users/rotimi/Documents/ng-faker/lib/fake.js:89:19)
    at Name.fullName (/Users/rotimi/Documents/ng-faker/lib/name.js:50:20)
    at Object.<anonymous> (/Users/rotimi/Documents/ng-faker/index.js:11:26)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
```
I'll raise a PR to fix this just wanted to let you guys know about it

**Comment by rotimi-babalola** [comment]
This fix can go out in the next version, I don't think this should stop us from releasing v1.0.0

**Comment by BolajiOlajide** [comment]
Hey @rotimi-babalola 
How about we throw an error whenever a user sets an invalid locale.

What do you think?

**Comment by BolajiOlajide** [comment]
Fixed.
